name: reborn_fe
description: "AI 기반 스마트 업사이클링 플랫폼 리본"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0          # HTTP 통신
  provider: ^6.1.2     # 상태관리
  kakao_flutter_sdk_user: ^1.9.1  # 카카오 로그인
  flutter_naver_login: ^2.1.1     # 네이버 로그인

  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  google_mlkit_image_labeling: ^0.13.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # assets 경로를 추가합니다.
  assets:
    - assets/images/
    - assets/icons/

  # fonts 를 추가합니다.
  fonts:
    - family: RebornFont
      fonts:
        - asset: assets/fonts/OwnglyphSeoJyeonii.ttf
